name: Auto Squash Merge with Author Change

on:
  pull_request:
    types:
      - closed  # PR이 Merge되거나 Closed될 때 실행됨

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # PR이 Merge된 경우에만 실행
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "UbridgeDev"
          git config user.email "ubridgedev0@gmail.com"

      - name: Get latest main branch
        run: |
          git checkout main
          git pull origin main

      - name: Recommit with new author
        run: |
          git commit --amend --no-edit --author="UbridgeDev <ubridgedev0@gmail.com>"
          git push --force origin main
